sudo : required
dist : trusty
group : edge

compiler:
    - gcc
    - clang
os:
    - linux
    - osx

branches:
    only:
        - master
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
            - hrani@ncbs.res.in

        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./_travis/prepare_linux.sh ; fi


script:
    - ./build_on_travis.sh
